# Generated by Django 2.0.7 on 2018-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20181018_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='upload_date',
            field=models.DateField(default='1980-01-01'),
            preserve_default=False,
        ),
    ]
