# Generated by Django 2.0.7 on 2018-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20181025_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
